[package]
name = "example-onnx-gpt-neo"
version = "0.1.0"
authors = ["JoFrost <mehdi.bessaa@mithrilsecurity.io>"]
license = "MIT/Apache-2.0"
edition = "2018"

[dependencies]
image = "0.24.1"
env_logger = "*"
tract-onnx = { path = "../../onnx" }
