[package]
name = "tract-onnx"
version = "0.17.2-pre"
authors = ["Mathieu Poumeyrol <kali@zoy.org>"]
license = "MIT/Apache-2.0"
description = "Tiny, no-nonsense, self contained, TensorFlow and ONNX inference"
repository = "https://github.com/snipsco/tract"
keywords = [ "TensorFlow", "NeuralNetworks", "ONNX" ]
categories = [ "science" ]
autobenches = false
edition = "2018"
exclude = [ "test_cases" ]

[features]
untrusted_fs = ["tract-nnef/untrusted_fs"]

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
bytes = "1.0.1"
derive-new = "0.5.9"
educe = "0.4.18"
log = "0.4.14"
num-integer = "0.1.44"
prost = "0.10.0"
smallvec = "1.6.1"
tract-hir = { version = "0.17.2-pre", path = "../hir" }
tract-nnef = { version = "0.17.2-pre", path = "../nnef" }
tract-onnx-opl = { version = "0.17.2-pre", path = "../onnx-opl" }
rand = "0.8.4"

[target.'cfg(all(not(target_arch = "wasm32"), not(target_env = "sgx")))'.dependencies]
mapr = "0.8.0"

[build-dependencies]
prost-build = "0.10.0"
